name: Run PyTest on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-merge:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai pytest

    - name: Set OpenAI API Key
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run PyTest
      run: pytest test_addition.py

    - name: Enable Auto-Merge
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        MERGE_METHOD: squash
